### ISSUE TITLE
Add hooks descriptions in the .pre-commit-config.yml file

### ISSUE THREAD

**Issue by michaltomczuk** [opsd-io/terraform-module-template#44]
Make all the pre-commit hooks more descriptive. 

Example: 

```yaml
      - id: check-yaml
        name: check yaml
        description: checks yaml files for parseable syntax.
        entry: check-yaml
        language: python
        types: [yaml]
```
